---
# tasks file for ansible-role-research_workstation

## update apt cache

- name: "update apt cache"
  apt: >
    update_cache=yes
    cache_valid_time=43200
  tags: [ 'packages' ]

## install utilities

- name: "Utilities - ensure for `curl`"
  apt: >
    update_cache=yes
    name={{ item }}
    state={{ fsl_state }}
  with_items:
    - curl
  tags: [ 'packages', 'utilities' ]

# Display

## Download resources

- name: "Download version {{ display_version }} of Display from Github"
  get_url:
    url: '{{ display_github_url }}'
    dest: 'sys/sw/ubuntu/12.04/display/{{ display_version }}/mni-display_2.0-5.deb'
  tags: [ 'packages', 'display' ]

- name: "Install the lastest version of Display for  Ubuntu 12.04"
  apt:
    deb: 'sys/sw/ubuntu/12.04/display/{{ display_version }}/mni-display_2.0-5.deb'
    state: present
  tags: [ 'packages', 'display' ]

- command: cp -r /opt/mni-display /opt/mni-display-{{ display_version }}
  args:
    chdir: /
    creates: /opt/mni-display-{{ display_version }}/bin/Display

# minc

## Download resources

- name: "Download latest stable version of minc toolkit for ubuntu 12.04 from Github"
  get_url:
    url: '{{ minc_github_stable_package_url }}'
    dest: '{{ minc_local_resource_path }}'
  tags: [ 'packages', 'minc' ]


- name: "Install the lastest version of minc toolkit for Ubuntu 12.04 available on Github"
  apt:
    deb: '{{ minc_local_resource_path }}'
    state: present
  tags: [ 'packages', 'minc' ]

- command: cp -r /opt/minc /opt/minc-{{ minc_version }}
  args:
    chdir: /
    creates: /opt/minc-{{ minc_version }}/bin/mincinfo
